### ISSUE TITLE
Role Validation 

### ISSUE THREAD

**Issue by mikweb** [nova-framework/cms#2]
The role name can be one word :
The pattern in  cms/app/Controllers/Admin/Roles.php must be changed from: 
`$pattern = '~^(?:[\p{L}\p{Mn}\p{Pd}\'\x{2019}]+(?:$|\s+)){2,}$~u';`
To:
`$pattern = '~^(?:[\p{L}\p{Mn}\p{Pd}\'\x{2019}]+(?:$|\s+)){1,}$~u';`

The framwork repositorie resolve this.

**Comment by daveismyname** [comment]
I must had upgraded this at some point at this is already there.
