### ISSUE TITLE
nova_pages table not found

### ISSUE THREAD

**Issue by vahidalvandi** [nova-framework/cms#4]
i try to test this i import all *.sql in script folder but have error 

Nova\Database\QueryException thrown with message "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nova_cms.nova_pages' doesn't exist (SQL: select * from `nova_pages` where `id` = 1 limit 1)"

Stacktrace:
#27 Nova\Database\QueryException in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Database\Connection.php:554
#26 Nova\Database\Connection:runQueryCallback in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Database\Connection.php:523
#25 Nova\Database\Connection:run in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Database\Connection.php:268
#24 Nova\Database\Connection:select in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Database\Query\Builder.php:1334
#23 Nova\Database\Query\Builder:runSelect in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Database\Query\Builder.php:1324
#22 Nova\Database\Query\Builder:getFresh in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Database\Query\Builder.php:1311
#21 Nova\Database\Query\Builder:get in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Database\ORM\Builder.php:394
#20 Nova\Database\ORM\Builder:getModels in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Database\ORM\Builder.php:155
#19 Nova\Database\ORM\Builder:get in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Database\ORM\Builder.php:129
#18 Nova\Database\ORM\Builder:first in D:\xampp\htdocs\gitlab\nova_cms\app\Controllers\Pages.php:17
#17 App\Controllers\Pages:fetch in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Routing\Controller.php:240
#16 call_user_func_array in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Routing\Controller.php:240
#15 Nova\Routing\Controller:callAction in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Routing\ControllerDispatcher.php:91
#14 Nova\Routing\ControllerDispatcher:call in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Routing\ControllerDispatcher.php:60
#13 Nova\Routing\ControllerDispatcher:dispatch in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Routing\Router.php:958
#12 Nova\Routing\Router:Nova\Routing\{closure} in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Routing\Route.php:128
#11 call_user_func_array in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Routing\Route.php:128
#10 Nova\Routing\Route:run in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Routing\Router.php:1026
#9 Nova\Routing\Router:dispatchToRoute in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Routing\Router.php:994
#8 Nova\Routing\Router:dispatch in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Foundation\Application.php:749
#7 Nova\Foundation\Application:dispatch in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Foundation\Application.php:717
#6 Nova\Foundation\Application:handle in D:\xampp\htdocs\gitlab\nova_cms\shared\Http\ContentGuard.php:62
#5 Shared\Http\ContentGuard:handle in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Session\Middleware.php:77
#4 Nova\Session\Middleware:handle in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Cookie\Queue.php:49
#3 Nova\Cookie\Queue:handle in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Cookie\Guard.php:54
#2 Nova\Cookie\Guard:handle in D:\xampp\htdocs\gitlab\nova_cms\vendor\stack\builder\src\Stack\StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in D:\xampp\htdocs\gitlab\nova_cms\vendor\nova-framework\system\src\Foundation\Application.php:615
#0 Nova\Foundation\Application:run in D:\xampp\htdocs\gitlab\nova_cms\public\index.php:44

**Comment by daveismyname** [comment]
ah I had old the script folder I've removed all scripts and added a single cms.sql file. https://github.com/nova-framework/cms/blob/master/scripts/cms.sql
